WebUI/ViewModels/Sites/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.ViewModels.Sites
{
    public class ListViewModel
    {
        public List<SiteItemDetailsViewModel> Sites { get; set; }
        public int TotalSites { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
    }
}

WebUI/ViewModels/Sites/SiteEditViewModel.cs
using Application.DTOs;
using Application.Items.SiteItems.Commands.EditSiteItem;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.ViewModels.Sites
{
    public class SiteEditViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Host { get; set; }
    }
}

WebUI/ViewModels/Sites/SiteItemDetailsViewModel.cs
using Application.Common.Models;
using Application.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.ViewModels.Sites
{
    public class SiteItemDetailsViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Host { get; set; }
    }
}

WebUI/ViewModels/Sites/SiteItemPanelViewModel.cs
using Application.Common.Models;
using Application.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.ViewModels.Sites
{
    public class SiteItemPanelViewModel
    {
        public SiteItemDetailsViewModel SiteItemDetails { get; set; }
        public List<SiteLinkItemDetailsViewModel> Links { get; set; }
        public SiteEditViewModel SiteEditViewModel { get; set; }
    }
}

WebUI/ViewModels/Sites/SiteLinkItemDetailsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebUI.ViewModels.Sites
{
    public class SiteLinkItemDetailsViewModel
    {
        public int LinkId { get; set; }
        public int SiteId { get; set; }
        [Required]
        [RegularExpression(@"(\/)(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?", ErrorMessage = "Must be valid url relative to the host.")]
        [MaxLength(300)]
        public string Url { get; set; }
    }
}

WebUI/Controllers/CoreWebVitalsToolController.cs
using Application.Common.BackgroundTasks.Tasks;
using Application.Common.Interfaces;
using Application.Common.Models;
using Application.DTOs;
using Application.Interfaces;
using Application.Items.CWVInfo.Commands;
using Application.Items.CWVInfo.Queries;
using Application.Items.SiteItems.Queries;
using Application.Items.SiteLinkItems.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using WebUI.Extensions;
using WebUI.ViewModels.CoreWebVitalsTool;

namespace WebUI.Controllers
{
    public class CoreWebVitalsToolController : ControllerBase
    {
        private readonly IAuthorizerService authorizerService;
        private readonly IApplicationDbContext context;
        private readonly ITasksManager tasksManager;

        public CoreWebVitalsToolController(IAuthorizerService authorizerService, IApplicationDbContext context, ITasksManager tasksManager)
        {
            this.authorizerService = authorizerService;
            this.context = context;
            this.tasksManager = tasksManager;
        }

        [Route("cwvtool/{siteId}")]
        public async Task<IActionResult> Index(int siteId)
        {
            // Create query
            GetSiteItemQuery getSiteItemQuery = new GetSiteItemQuery(siteId);

            // Validate if query can be executed by this user
            if (!await this.authorizerService.Authorize<GetSiteItemQuery>(getSiteItemQuery))
                return NotFound();

            // Execute query to retrieve site data
            SiteItemDto existingSiteItem = await Mediator.Send(getSiteItemQuery);

            // Get list of all site links
            GetSiteLinkItemsWithPaginationQuery getSiteLinkItems = new GetSiteLinkItemsWithPaginationQuery(existingSiteItem.Id) { PageSize = 9999 }; // TODO: Create another Query without pages
            PaginatedList<SiteLinkItemDto> existingSiteLinkItems = await Mediator.Send(getSiteLinkItems);

            // Build model
            CoreWebVitalsToolMainViewModel viewModel = new CoreWebVitalsToolMainViewModel();
            viewModel.SiteItemDetails = new ViewModels.Sites.SiteItemDetailsViewModel();
            viewModel.SiteItemDetails.MapFrom(existingSiteItem);
            viewModel.Links = new List<LinkCWVInfoViewModel>();
            foreach (var link in existingSiteLinkItems.Items)
            {
                LinkCWVInfoViewModel linkCWVInfoViewModel = new LinkCWVInfoViewModel();
                GetLatestCWVInfoByLinkIdQuery getSingleCWVInfoQuery = new GetLatestCWVInfoByLinkIdQuery(link.Id);
                var cwvInfoDto = await Mediator.Send(getSingleCWVInfoQuery);
                linkCWVInfoViewModel.MapFrom(link, cwvInfoDto);
                viewModel.Links.Add(linkCWVInfoViewModel);
            }

            return View(viewModel);
        }

        [HttpPost]
        [Route("ScanVitals/{siteId}")]
        public async Task<IActionResult> ScanSiteVitals(int siteId)
        {
            // Get Site entry data
            GetSiteItemQuery getSiteItemQuery = new GetSiteItemQuery(siteId);
            if (!await this.authorizerService.Authorize<GetSiteItemQuery>(getSiteItemQuery))
                return NotFound();

            SiteItemDto existingSiteItem = await Mediator.Send(getSiteItemQuery);

            // Get Site Links
            // FYI - while pagination supported on Query, in the current application it is not used in user views, so we set default page size to 1000.
            GetSiteLinkItemsWithPaginationQuery getSiteLinkItems = new GetSiteLinkItemsWithPaginationQuery(siteId) { PageSize = 1000 };
            PaginatedList<SiteLinkItemDto> existingSiteLinkItems = await Mediator.Send(getSiteLinkItems);

            // WORK IN PROGRESS
            // TODO: This code is here temporarry until program evolves further and we start using historical scans data on the views.
            // Remove old CWV data
            // This old data could be stored for later analysis, but for performance and storage reasons we are removing old data.
            DeleteCWVInfoEntriesForSiteCommand deleteCWVInfoEntriesForSiteCommand = new DeleteCWVInfoEntriesForSiteCommand(siteId);
            await Mediator.Send(deleteCWVInfoEntriesForSiteCommand);
            // ---WORK IN PROGRESS

            // Init new CWV scan
            InitCWVScanCommand initCWVScanCommand = new InitCWVScanCommand(existingSiteLinkItems.Items, existingSiteItem.Host);
            await Mediator.Send(initCWVScanCommand);

            return RedirectToAction("Index", new { siteId });
        }


        [Route("ShowVitals/{id}")]
        [Produces("text/html")]
        public async Task<ActionResult<string>> ShowVitals(int id)
        {
            GetLatestCWVInfoByLinkIdQuery getSingleCWVInfoQuery = new GetLatestCWVInfoByLinkIdQuery(id);
            var result = await Mediator.Send(getSingleCWVInfoQuery);
            return Content(result.Source, "text/html");
        }
    }
}

WebUI/Controllers/DiffToolController.cs
using Application.Common.BackgroundTasks.Enums;
using Application.Common.BackgroundTasks.Tasks;
using Application.Common.Interfaces;
using Application.Common.Models;
using Application.DTOs;
using Application.Interfaces;
using Application.Items.ClientCode.Commands;
using Application.Items.ClientCode.Queries;
using Application.Items.DiffIgnoreRegex.Commands;
using Application.Items.DiffIgnoreRegex.Queries;
using Application.Items.SiteItems.Commands.DeleteSiteItem;
using Application.Items.SiteItems.Queries;
using Application.Items.SiteLinkItems.Queries;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using WebUI.Extensions;
using WebUI.ViewModels.DiffTool;
using WebUI.ViewModels.Sites;

namespace WebUI.Controllers
{
    public class DiffToolController : ControllerBase
    {
        private readonly ILogger<SitesController> logger;
        private readonly IMapper mapper;
        private readonly IAuthorizerService authorizerService;
        private readonly ITasksManager tasksManager;
        private readonly IApplicationDbContext context;

        public DiffToolController(ILogger<SitesController> logger, IMapper mapper, IAuthorizerService authorizerService, ITasksManager tasksManager, IApplicationDbContext context)
        {
            this.logger = logger;
            this.mapper = mapper;
            this.authorizerService = authorizerService;
            this.tasksManager = tasksManager;
            this.context = context;
        }

        [Route("DiffTool/{siteId}")]
        public async Task<IActionResult> Index(int siteId)
        {
            GetSiteItemQuery getSiteItemQuery = new GetSiteItemQuery(siteId);
            if (!await this.authorizerService.Authorize<GetSiteItemQuery>(getSiteItemQuery))
                return NotFound();

            SiteItemDto existingSiteItem = await Mediator.Send(getSiteItemQuery);

            GetSiteLinkItemsWithPaginationQuery getSiteLinkItems = new GetSiteLinkItemsWithPaginationQuery(existingSiteItem.Id) { PageSize=9999 }; // TODO: Create another Query without pages
            PaginatedList<SiteLinkItemDto> existingSiteLinkItems = await Mediator.Send(getSiteLinkItems);

            GetClientCodesQuery getClientCodes = new GetClientCodesQuery(siteId);
            List<ClientCodeDto> clientCode = await Mediator.Send(getClientCodes);

            GetReferenceClientCodesQuery getReferenceClientCodes = new GetReferenceClientCodesQuery(siteId);
            List<ClientCodeDto> refClientCodes = await Mediator.Send(getReferenceClientCodes);

            GetDiffIgnoreRegexQuery getDiffIgnoreRegexQuery = new GetDiffIgnoreRegexQuery(siteId);
            DiffIgnoreRegexDto diffIgnoreRegexDto = await Mediator.Send(getDiffIgnoreRegexQuery);

            DiffToolMainViewModel viewModel = new DiffToolMainViewModel();
            viewModel.MapFrom(existingSiteItem, existingSiteLinkItems, clientCode, refClientCodes, diffIgnoreRegexDto);

            return View(viewModel);
        }

        [HttpPost]
        [Route("UpdateRegex/{siteId}")]
        public async Task<IActionResult> UpdateRegex([FromForm]string diffIgnoreRegex, int siteId)
        {
            EditIgnoreRegexCommand editIgnoreRegexCommand = new EditIgnoreRegexCommand() { RegexLines = diffIgnoreRegex, SiteItemId = siteId };
            await Mediator.Send(editIgnoreRegexCommand);
            return RedirectToAction("Index", new { siteId });
        }

        [HttpPost]
        [Route("ScanSite/{siteId}/{mode=0}")]
        public async Task<IActionResult> ScanSite(int siteId, int mode)
        {
            //TODO: use authorization service to check if user is allowed to execute queries and commands

            GetSiteItemQuery getSiteItemQuery = new GetSiteItemQuery(siteId);
            SiteItemDto siteItem = await Mediator.Send(getSiteItemQuery);

            GetSiteLinkItemsWithPaginationQuery getSiteLinkItems = new GetSiteLinkItemsWithPaginationQuery(siteId) { PageSize=9999 };
            PaginatedList<SiteLinkItemDto> existingSiteLinkItems = await Mediator.Send(getSiteLinkItems);

            // IN PROGRESS
            // Remove old scans for performance reasons, because right now historical records are not used in the application.
            DeleteClientCodesBySiteIdCommand deleteClientCodesBySiteIdCommand = new DeleteClientCodesBySiteIdCommand(siteId, (ClientCodeRequestMode)mode);
            await Mediator.Send(deleteClientCodesBySiteIdCommand);
            // ---IN PROGRESS

            // Initialise new source code scan.
            foreach (var link in existingSiteLinkItems.Items)
            {
                var fullUrl = siteItem.Host + link.Url;
                var clienCodeRecord = new Domain.Entities.ClientCode()
                {
                    IsDownloadingCompleted = false,
                    UrlUsed = fullUrl,
                    SiteLinkItemId = link.Id
                };

                // Create initial values in db (in progress db entries)
                // TODO: to be moved to QUERY instead
                this.context.ClientCode.Add(clienCodeRecord);
                await this.context.SaveChangesAsync(new System.Threading.CancellationToken());
                // Set current clients code IF Mode is set to set current site state
                if (mode == (int)ClientCodeRequestMode.CurrentState)
                {
                    var refClientCode = this.context.ReferenceClientCode.Where(rcc => rcc.SiteLinkItemId == clienCodeRecord.SiteLinkItemId).FirstOrDefault();

                    if (refClientCode == null)
                    {
                        refClientCode = new Domain.Entities.ReferenceClientCode() { ClientCode = clienCodeRecord, SiteLinkItemId = clienCodeRecord.SiteLinkItemId };
                        this.context.ReferenceClientCode.Add(refClientCode);
                    }
                    else
                    {
                        refClientCode.ClientCode = clienCodeRecord;
                        refClientCode.SiteLinkItemId = clienCodeRecord.SiteLinkItemId;
                    }
                }
                await this.context.SaveChangesAsync(new System.Threading.CancellationToken());

                // Create background task to download client codes.
                GetClientCodeTask task = new GetClientCodeTask() { ClientCodeId = clienCodeRecord.Id, Url = fullUrl };
                tasksManager.EnqueueTask(task);
            }

            return RedirectToAction("Index", new { siteId });
        }

        [Route("DiffTool/Compare/{refCodeId}/{compareToCodeId}")]
        public async Task<IActionResult> Compare(int refCodeId, int compareToCodeId)
        {
            GetClientCodeByIdQuery refCodeQuery = new GetClientCodeByIdQuery(refCodeId);
            var refCode = await Mediator.Send(refCodeQuery);

            GetClientCodeByIdQuery compareToCodeQuery = new GetClientCodeByIdQuery(compareToCodeId);
            ClientCodeDto compareToCode = await Mediator.Send(compareToCodeQuery);

            DiffViewViewModel model = new DiffViewViewModel();

            GetSiteLinkItemQuery getSiteLinkItemQuery = new GetSiteLinkItemQuery(refCode.SiteLinkItemId);
            var refSiteLinkItem = await Mediator.Send(getSiteLinkItemQuery);

            GetDiffIgnoreRegexQuery getDiffIgnoreRegexQuery = new GetDiffIgnoreRegexQuery(refSiteLinkItem.SiteItemId);
            DiffIgnoreRegexDto diffIgnoreRegexDto = await Mediator.Send(getDiffIgnoreRegexQuery);

            refCode.ApplyRegexDiffIgnore(diffIgnoreRegexDto);
            compareToCode.ApplyRegexDiffIgnore(diffIgnoreRegexDto);

            model.MapFrom(refCode, compareToCode);

            return View(model);
        }
    }
}

WebUI/Views/Sites/Edit.cshtml
@model WebUI.ViewModels.Sites.SiteEditViewModel

<div class="row justify-content-center c-new-site-editor-cont mt-5">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label new-site-edit-lbl"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Host" class="control-label new-site-edit-lbl"></label>
                <input asp-for="Host" class="form-control" />
                <span asp-validation-for="Host" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebUI/Views/Sites/List.cshtml
@model WebUI.ViewModels.Sites.ListViewModel
@inject IAuthorizerService AuthorizerService

@{
    ViewData["Title"] = "List";
}

<p>
    <a asp-action="Edit" class="btn btn-primary">Add New Site</a>
</p>


<div class="c-sites-list-container">
    @if (Model.Sites == null || Model.Sites.Count() == 0)
            {
                <div class="no-sites-msg">No sites available.</div>
            }
    @foreach (var site in Model.Sites)
    {
        <div class="c-site-container">
            <div class="c-site-title">@site.Title</div>
            <div class="c-site-host">@site.Host</div>
            <div class="c-tools-list mt-3">
                <a class="btn btn-primary" asp-area="" asp-controller="DiffTool" asp-action="Index" asp-route-siteId="@site.Id">Diff Tool</a>
                <a class="btn btn-primary" asp-area="" asp-controller="CoreWebVitalsTool" asp-action="Index" asp-route-siteId="@site.Id">CWV Tool</a>
            </div>
            <div class="c-site-manage-btns">
                @Html.ActionLink("Edit", "Panel", new { id = site.Id }) |
                <a href="#" data-toggle="modal" data-target="#deleteModal" data-siteId="@site.Id">Delete</a>
            </div>
        </div>
    }
</div>

@*Delete Modal*@
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Site?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this site? All data associated with this site will be lost.</p>
            </div>
            <div class="modal-footer">
                <button type="button" id="deleteBtn" class="btn btn-danger">Delete!</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        $('#deleteModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var siteId = button.data('siteid'); // Extract siteId from data-siteId

            var modal = $(this);
            var delBtn = modal.find('#deleteBtn');
            delBtn.click(function () {
                postData('/api/sites/delete/' + siteId, {})
                    .then(status => {
                        location.reload();
                    });
            });
        });

        async function postData(url = '', data = {}) {
            const response = await fetch(url, {
                method: 'POST',
                mode: 'cors',
                cache: 'no-cache',
                credentials: 'same-origin',
                headers: {
                    'Content-Type': 'application/json'
                },
                referrerPolicy: 'no-referrer',
                body: JSON.stringify(data)
            });
            return response.status;
        }
    </script>
}

WebUI/Views/Sites/Panel.cshtml
@model WebUI.ViewModels.Sites.SiteItemPanelViewModel
@{
    var parms = new Dictionary<string, string>
{
        { "siteId", Model.SiteItemDetails.Id.ToString() }
    };
}
<div id="site-title" class="d-flex align-items-center">
    <div class="editable-site-title">@Model.SiteItemDetails.Title</div>
    <div class="ml-3">
        <div class="btn btn-sm btn-light" onclick="EditTitle()">Edit</div>
    </div>
</div>
<div id="edit-title-form" class="d-none">
    <form asp-action="EditSitePartial" method="post" class="form-edit-title">
        <div>
            @Html.EditorFor(m => m.SiteEditViewModel.Title, null, "Title")
            <input type="number" name="Id" value="@Model.SiteEditViewModel.Id" hidden />
            <input type="text" name="FieldName" value="Title" hidden />
            <input class="btn btn-sm btn-primary" type="submit" name="save" value="Save" />
            <div class="btn btn-sm btn-light" onclick="CancelEdit()">Cancel</div>
        </div>
        <span class="field-validation-valid" data-valmsg-for="Title" data-valmsg-replace="true"></span>
    </form>
</div>

<div id="site-host" class="d-flex align-items-center">
    <div class="editable-site-host">@Model.SiteItemDetails.Host</div>
    <div class="ml-3">
        <div class="btn btn-sm btn-light" onclick="EditHost()">Edit</div>
    </div>
</div>
<div id="edit-host-form" class="d-none">
    <form asp-action="EditSitePartial" method="post" class="form-edit-host">
        <div>
            @Html.EditorFor(m => m.SiteEditViewModel.Host, null, "Host")
            <input type="number" name="Id" value="@Model.SiteEditViewModel.Id" hidden />
            <input type="text" name="FieldName" value="Host" hidden />
            <input class="btn btn-sm btn-primary" type="submit" name="save" value="Save" />
            <div class="btn btn-sm btn-light" onclick="CancelEdit()">Cancel</div>
        </div>
        <span class="field-validation-valid" data-valmsg-for="Host" data-valmsg-replace="true"></span>
    </form>
</div>

<div class="mt-3">
    <div display-if="Model.Links.Count == 0" class="no-links-available">No site links available yet.</div>
    <div id="list-of-links-container">
        @foreach (var link in Model.Links)
        {
            <div id="link_@link.LinkId" class="d-flex">
                <div class="mr-3 has-child-hidden d-flex">
                    <div class="link-text-container"><a href="@Model.SiteItemDetails.Host@link.Url" target="_blank">@link.Url</a></div>
                    <div class="child-hidden ml-3">
                        <div class="btn btn-sm btn-light" onclick="Edit(@link.LinkId)">edit</div>
                        <form asp-action="DeleteSiteLink" method="post">
                            @Html.Hidden("LinkId", link.LinkId)
                            @Html.Hidden("SiteId", link.SiteId)
                            <input class="btn btn-sm btn-light" type="submit" name="delete" value="Delete" />
                        </form>
                    </div>
                </div>
            </div>
            <div class="d-none" id="form_@link.LinkId">
                @{ await Html.RenderPartialAsync("_SiteLinkItemEditorPartial", link); }
            </div>
        }
    </div>
    <div id="addNewBtn" class="btn btn-primary mt-2" onclick="AddNew()">Add New</div>
    <div id="newForm" class="d-none">@{ await Html.RenderPartialAsync("_SiteLinkItemEditorPartial", new WebUI.ViewModels.Sites.SiteLinkItemDetailsViewModel() { SiteId = Model.SiteItemDetails.Id, LinkId = 0, Url = "" }); }</div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        let visibleFormId = 0;

        function Edit(linkId) {
            CancelEdit(visibleFormId);
            visibleFormId = linkId;
            document.getElementById("link_" + linkId).classList.remove("d-flex");
            document.getElementById("link_" + linkId).classList.add("d-none");
            document.getElementById("form_" + linkId).classList.remove("d-none");
        }

        function CancelEdit(linkId) {
            document.getElementById("addNewBtn").classList.remove("d-none");
            document.getElementById("newForm").classList.add("d-none");

            document.getElementById("site-title").classList.remove("d-none");
            document.getElementById("site-title").classList.add("d-flex");
            document.getElementById("edit-title-form").classList.add("d-none");

            document.getElementById("site-host").classList.remove("d-none");
            document.getElementById("site-host").classList.add("d-flex");
            document.getElementById("edit-host-form").classList.add("d-none");

            if (document.getElementById("link_" + linkId) == null)
                return;
            document.getElementById("link_" + linkId).classList.add("d-flex");
            document.getElementById("link_" + linkId).classList.remove("d-none");
            document.getElementById("form_" + linkId).classList.add("d-none");
        }

        function AddNew() {
            CancelEdit(visibleFormId);
            document.getElementById("addNewBtn").classList.add("d-none");
            document.getElementById("newForm").classList.remove("d-none");
        }

        function EditTitle() {
            CancelEdit(visibleFormId);
            document.getElementById("site-title").classList.add("d-none");
            document.getElementById("site-title").classList.remove("d-flex");
            document.getElementById("edit-title-form").classList.remove("d-none");
        }

        function EditHost() {
            CancelEdit(visibleFormId);
            document.getElementById("site-host").classList.add("d-none");
            document.getElementById("site-host").classList.remove("d-flex");
            document.getElementById("edit-host-form").classList.remove("d-none");
        }
    </script>
}