WebUI/Controllers/SitesController.cs
using Application.Interfaces;
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using Application.Common.Models;
using Application.DTOs;
using Application.Common.Interfaces;
using Application.Items.SiteItems.Commands.EditSiteItem;
using Application.Items.SiteItems.Queries;
using Application.Items.SiteLinkItems.Queries;
using WebUI.ViewModels.Sites;
using WebUI.Extensions;
using Application.Items.SiteItems.Commands.DeleteSiteItem;
using Application.Items.SiteLinkItems.Commands.DeleteSiteLinkItem;
using Application.Items.SiteLinkItems.Commands.EditSiteLinkItem;
using System.ComponentModel.DataAnnotations;

namespace WebUI.Controllers
{
    [Authorize]
    public class SitesController : ControllerBase
    {
        private readonly ILogger<SitesController> _logger;
        private readonly IMapper _mapper;
        private readonly Application.Common.Interfaces.IAuthorizerService authorizerService;

        public SitesController(ILogger<SitesController> logger, IMapper mapper, IAuthorizerService authorizerService)
        {
            _logger = logger;
            _mapper = mapper;
            this.authorizerService = authorizerService;
        }
        public async Task<IActionResult> IndexAsync([FromQuery] GetSiteItemsWithPaginationQuery query)
        {
            // Paging currently is not implemented on the front end, so we do set a default value to a large number.
            query.PageSize = 1000;
            PaginatedList<SiteItemDto> data = await Mediator.Send(query);
            ListViewModel model = new ListViewModel();
            model.MapFrom(data);
            return View("List", model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            SiteItemDto existingSiteItem = null;
            EditSiteItemCommand editSiteItemCommand = null;

            if (id.HasValue)
            {
                existingSiteItem = await Mediator.Send(new GetSiteItemQuery(id.Value));

                if (existingSiteItem == null)
                    return NotFound();

                editSiteItemCommand = new EditSiteItemCommand();
                editSiteItemCommand.Id = existingSiteItem.Id;
            }

            if (!await this.authorizerService.Authorize<EditSiteItemCommand>(editSiteItemCommand))
                return NotFound();

            SiteEditViewModel siteEditViewModel = new SiteEditViewModel();
            siteEditViewModel.MapFrom(existingSiteItem);

            return View(siteEditViewModel); // TODO: Try inheriting to some ViewModel and check if front end validations still apply?
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SiteEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                EditSiteItemCommand command = model.ToEditCommand();
                await Mediator.Send(command);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Panel(int id)
        {
            GetSiteItemQuery getSiteItemQuery = new GetSiteItemQuery(id);
            if (!await this.authorizerService.Authorize<GetSiteItemQuery>(getSiteItemQuery))
                return NotFound();

            SiteItemDto existingSiteItem = await Mediator.Send(getSiteItemQuery);
            GetSiteLinkItemsWithPaginationQuery getSiteLinkItems = new GetSiteLinkItemsWithPaginationQuery(existingSiteItem.Id);
            PaginatedList<SiteLinkItemDto> existingSiteLinkItem = await Mediator.Send(getSiteLinkItems);

            SiteItemPanelViewModel detailsViewModel = new SiteItemPanelViewModel();
            detailsViewModel.MapFrom(existingSiteItem, existingSiteLinkItem);

            return View(detailsViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditLink([FromForm] SiteLinkItemDetailsViewModel model)
        {
            EditSiteLinkItemCommand command = model.ToEditCommand();
            if (ModelState.IsValid)
            {
                await Mediator.Send(command);
                return RedirectToAction("Panel", new { id = model.SiteId });
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSiteLink([FromForm] int linkId, [FromForm] int siteId)
        {
            DeleteSiteLinkItemCommand command = new DeleteSiteLinkItemCommand(linkId);
            if (ModelState.IsValid)
            {
                var sucess = await Mediator.Send(command);
                if (sucess)
                {
                    return RedirectToAction("Panel", new { id = siteId });
                }
                else
                {
                    return BadRequest();
                }
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditSitePartial(SiteEditViewModel model, [FromForm] string fieldName)
        {
            SiteItemDto existingSiteItem;
            existingSiteItem = await Mediator.Send(new GetSiteItemQuery(model.Id));

            if (existingSiteItem == null)
                return BadRequest();

            SiteEditViewModel siteEditViewModel = new SiteEditViewModel()
            {
                Host = existingSiteItem.Host,
                Id = existingSiteItem.Id,
                Title = existingSiteItem.Title
            };

            var value = model.GetType().GetProperty(fieldName).GetValue(model, null);
            siteEditViewModel.GetType().GetProperty(fieldName).SetValue(siteEditViewModel, value, null);

            EditSiteItemCommand command = siteEditViewModel.ToEditCommand();
            await Mediator.Send(command);
            return RedirectToAction("Panel", new { id = siteEditViewModel.Id });
        }
    }
}

WebUI/Views/Shared/_ClientCodeStatus.cshtml
@model WebUI.ViewModels.DiffTool.ClientCodeListEntryViewModel

<div class="c-diff-stat-container">
    @if (Model == null)
    {
        <div class="c-diff-downloading">No data available.</div>
        return;
    }

    @if (!Model.IsDownloadingCompleted)
    {
        <div class="c-diff-downloading">Downloading...</div>
    }
    else
    {
        <div class="c-diff-stat-single">
            <div class="c-diff-ttl">Status:</div>
            <div>@Model.ResponseCode</div>
        </div>
        <div class="">
            <div class="c-diff-ttl">Url Used:</div>
            <div class="c-global-truncate-text">@Model.UrlUsed</div>
        </div>
    }

</div>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMasterAide</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/additionals.css" />
    @await RenderSectionAsync("HeadScripts", required: false)
</head>
<body>
    <header id="header-container">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMasterAide</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (CurrentUserService.UserId != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sites" asp-action="Index">Sites</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer-container" class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebMasterAide
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_SiteLinkItemEditorPartial.cshtml
@model WebUI.ViewModels.Sites.SiteLinkItemDetailsViewModel
<div class="row">
    <div class="" id="link-editor-form">
        <form asp-action="EditLink" class="d-flex" id="site-link-editor-form">
            <input asp-for="LinkId" class="form-control" type="hidden" />
            <input asp-for="SiteId" class="form-control" type="hidden" />
            <div class="">
                <label asp-for="Url" class="control-label" hidden>Url</label>
                <input asp-for="Url" class="form-control form-control-sm" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div>
                <input type="submit" value="Save" class="btn btn-sm btn-primary" />
                <div class="btn btn-sm btn-light" onclick="CancelEdit(@Model.LinkId)">Cancel</div>
            </div>
        </form>
    </div>
</div>